"""Initial schema with indexes

Revision ID: 4e749bfac9a8
Revises: 
Create Date: 2026-04-28 13:09:04.402260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e749bfac9a8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_chunks_document_id'), 'chunks', ['document_id'], unique=False)
    op.create_index(op.f('ix_chunks_frequency_score'), 'chunks', ['frequency_score'], unique=False)
    op.create_index(op.f('ix_chunks_tier'), 'chunks', ['tier'], unique=False)
    op.create_index(op.f('ix_chunks_topic_cluster_id'), 'chunks', ['topic_cluster_id'], unique=False)
    op.create_index(op.f('ix_documents_content_hash'), 'documents', ['content_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_content_hash'), table_name='documents')
    op.drop_index(op.f('ix_chunks_topic_cluster_id'), table_name='chunks')
    op.drop_index(op.f('ix_chunks_tier'), table_name='chunks')
    op.drop_index(op.f('ix_chunks_frequency_score'), table_name='chunks')
    op.drop_index(op.f('ix_chunks_document_id'), table_name='chunks')
    # ### end Alembic commands ###
